###########################################################
#                                                         #
# Copyright (c)                                           #
#                                                         #
# The Verifiable & Control-Theoretic Robotics (VECTR) Lab #
# University of California, Los Angeles                   #
#                                                         #
# Authors: Kenny J. Chen, Ryan Nemiroff, Brett T. Lopez   #
# Contact: {kennyjchen, ryguyn, btlopez}@ucla.edu         #
#                                                         #
###########################################################

dlio:

  frames:
    odom: odom
    baselink: camera_base
    lidar: depth_camera_link
    imu: imu_link


  map:
    waitUntilMove: false
    dense:
      filtered: false
    sparse:
      frequency: 10.0
      leafSize: 0.2

  odom:

    gravity: 9.84892

    imu:
      approximateGravity: true
      calibration:
        gyro: true
        accel: true
        time: 2
      bufferSize: 5000

    preprocessing:
      cropBoxFilter:
        size: 0.3
      voxelFilter:
        res: 0.025

    keyframe:
      threshD: 0.7
      threshR: 30.0

    submap:
      keyframe:
        knn: 20
        kcv: 20
        kcc: 20
    gicp:
      minNumPoints: 100
      kCorrespondences: 24
      maxCorrespondenceDistance: 0.6
      maxIterations: 70
      transformationEpsilon: 0.01
      rotationEpsilon: 0.01
      initLambdaFactor: 1e-9

    geo:
      Kp: 4.5
      Kv: 11.25
      Kq: 4.0
      Kab: 2.25
      Kgb: 1.0
      abias_max: 5.0
      gbias_max: 0.5
